demo/config/routes.rb
Rails.application.routes.draw do
  
  get 'tweet/search'
  

  root to: 'tweet#search'
  
  devise_for :users
  resources :userinfos

end

demo/app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :tweet
end

demo/app/models/retweet.rb
class Retweet < ActiveRecord::Base

  # validates :tweet_id, :retweet_user_id, :uniqueness => true
  belongs_to :tweet
  belongs_to :twitter_user
end

demo/app/models/tweet.rb
require 'tweet_model'

class Tweet < ActiveRecord::Base
   validates :tweet_id, :uniqueness => true
   has_one :twitter_user, :dependent => :destroy
   has_one :place, :dependent => :destroy
   has_many :retweets, :dependent => :destroy
   
  
  def self.search(search, country)#, city)
    @tweets = []
    if search == nil or search == ""
      return @tweets
      # search = ""
    end
    # if search == nil or search == ""
    #   search = " "
    # end
    if search
      constraint = {
        'text' => search,
        'country' => country
        # 'city' => city
      }

      x = UPENN::Twitter.get_instance
      # @tweets = []
      # x.search(constraint).each do |i|
      #   user_city = x.get_user(i[:user])[:location]
      #   if user_city == nil or user_city == ""
      #     next
      #   end
      #   puts '------------'
      #   puts user_city

      x.get_location_from_tweet_array(x.search(constraint)).each do |i|
        @tweets.push({
          :text => i[:text],
          :lat => i[:lat],
          :lng => i[:long],
          })
      end
    
    # loc = searchLocation(user_city)
        
    end
    return @tweets
  end
  # def self.makeLatLng(lat1, lng1, lat2, lng2)
  #   @polyline = Array.new

  # end

  # def self.searchLocation(city)
  #   geoinfo = Geocoder.search(city)
  #   return geoinfo.first.data["geometry"]["location"]
  # end
end

demo/app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
	validates :user_id, :uniqueness => true
  has_many :retweets, dependent: :destroy	
  belongs_to :tweet
end

demo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

demo/app/models/userinfo.rb
class Userinfo < ActiveRecord::Base

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  before_action :authenticate_user!
  
  def search
    keyword = params[:search]
    country = params[:country]
    
    # if keyword == nil or keyword == ""
    #   if country != nil and country != ""
    #     @notice = "keyword is needed!"
    #   end
    #   return
    # end


    if keyword == ""
      @notice = "Keyword is needed!"
      return
    elsif keyword == nil
      return
    end

    
    @tweets = Tweet.search(keyword, country)
    
    if @tweets.length == 0
      @notice = "Tweets not found!"
      return
    else
      @notice = "Tweets found!"
    end
    
   
     @hash = Gmaps4rails.build_markers(@tweets) do |tweet, marker|
       marker.lat tweet[:lat]
       marker.lng tweet[:lng]
       marker.infowindow tweet[:text]
     end
    
     # @line = Array.new
     #
     # @tweets.each do |tweet|
     #   newHash = Hash.new
     #   newHash['lat'] = tweet[:lat]
     #   newHash['lng'] = tweet[:lng]
     #   @line.push(newHash)
     # end
  end
end

demo/app/controllers/userinfos_controller.rb
require 'json'

class UserinfosController < ApplicationController
  before_action :set_userinfo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /userinfos
  # GET /userinfos.json
  def index
    # @userinfos = Userinfo.all
    @userinfo = Userinfo.where(id: current_user.id)[0]
    if @userinfo == nil
      # new user
      new_record = {'id' => current_user.id,
        'user_name' => current_user.email,
        'country' => '-'}
      Userinfo.create(new_record).save

      @userinfo = Userinfo.where(id: current_user.id)[0]
    end
  end

  # GET /userinfos/1
  # GET /userinfos/1.json
  def show
  end

  # GET /userinfos/new
  # def new
  #   @userinfo = Userinfo.new
  # end

  # GET /userinfos/1/edit
  def edit
  end

  # POST /userinfos
  # POST /userinfos.json

  # PATCH/PUT /userinfos/1
  # PATCH/PUT /userinfos/1.json
  def update
    respond_to do |format|
      if @userinfo.update(userinfo_params)
        format.html { redirect_to @userinfo, notice: 'Userinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @userinfo }
      # else
      #   format.html { render :edit }
      #   format.json { render json: @userinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userinfo
      # @userinfo = Userinfo.find(params[:id])
      @userinfo = Userinfo.find(current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userinfo_params
      params.require(:userinfo).permit(:user_name, :country, :city, :age)
    end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/tweet_helper.rb
module TweetHelper
end

demo/app/helpers/userinfos_helper.rb
module UserinfosHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweet Trend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/tweet/search.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<body>
<h1>Welcome to Tweet Trend</h1>

<p>You can search tweets by keyword!

  <%= form_tag userinfos_path, :method => 'get'  do %>


  <%= button_to "Personal Profile" %>

  <% end %>
  
  <%= form_tag destroy_user_session_path, :method => 'get'  do %>


  <%= button_to "Sign Out" %>

  <% end %>

</p>

<table>
  <tr>
    <td>
      <table>

      <%= form_tag tweet_search_path, :method => 'get'  do %>
      <tr>
        <td>
        <%= label_tag :search, "Keyword"%>
         <%= text_field_tag :search, params[:search]%>
       </td>
      </tr>
      <tr>
        <td>
         <%= label_tag :search, "Country"%>
         <%= text_field_tag :country, params[:country]%>
       </td>
      </tr>

      <tr>
        <td>
         <%= submit_tag "Search", :text => nil  %>
       </td>
      </tr>
       <% end %>
      </table>
    </td>

    <td>
      <div style='width: 800px;'>
        <div id="map" style='width: 800px; height: 400px;'>
        </div>
      </div>

      <script type="text/javascript">
          handler = Gmaps.build('Google');
          handler.buildMap({provider: {}, internal: {id: 'map'}}, function () {
              markers = handler.addMarkers(<%=raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              // polyline = <%=raw @line.to_json %>;
      //   handler.addPolyline(polyline, { strokeColor: '#FFFFEE',strokeOpacity: 1,
      // strokeWeight: 1});
      //   handler.bounds.extend(polyline[0]);
      //   handler.bounds.extend(polyline[polyline.length - 1]);
              handler.fitMapToBounds();

          });
      </script>
    </td>

  </tr>
</table>


<p id="notice"><%= @notice %>
</p>

<!-- <tr>

<td>
 -->

<% if @tweets != nil && @tweets != [] %>

    <table>
     
      <tbody>
      <% @tweets.each do |tweet| %>
          <tr>

            <td><%= tweet[:text] %></td>

          </tr>
      <% end %>
      </tbody>
    </table>

    <br>
<% end %>
<!-- </td>
</tr>
</table> -->
</body>

demo/app/views/userinfos/_form.html.erb
<%= form_for(@userinfo) do |f| %>
  <% if @userinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userinfo.errors.count, "error") %> prohibited this userinfo from being saved:</h2>

      <ul>
      <% @userinfo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/userinfos/edit.html.erb
<h1>Personal Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @userinfo %> |
<%= link_to 'Back', userinfos_path %>

demo/app/views/userinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Information</h1>
<% if @userinfo != nil and @userinfo != []%>
<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Country</th>
      <th>City</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
      <tr>
        <td><%= @userinfo.user_name %></td>
        <td><%= @userinfo.country %></td>
        <td><%= @userinfo.city %></td>
        <td><%= @userinfo.age %></td>
     <!--    <td><%= link_to 'Show', @userinfo %></td> -->
        <td><%= link_to 'Edit', edit_userinfo_path(@userinfo) %></td>
       <!--  <td><%= link_to 'Destroy', @userinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
  
  </tbody>
</table>

 <%= form_tag tweet_search_path, :method => 'get'  do %>


<%= button_to "Search" %>

 <% end %>

 <%= form_tag destroy_user_session_path, :method => 'get'  do %>


<%= button_to "Sign Out" %>

 <% end %>
<br>
<%end%>
<!-- ss -->

demo/app/views/userinfos/new.html.erb
<h1>New Userinfo</h1>
<!-- 
<%= render 'form' %> -->



<%= form_tag new_userinfo_path, :method => 'get'  do %>

<td>
	<%= label_tag :create, "name"%>
   <%= text_field_tag :user_name, params[:user_name]%>
</td>
<td>
	 <%= label_tag :create, "Country"%>
   <%= text_field_tag :country, params[:country]%>
</td>
<td>
	<%= label_tag :create, "City"%>
   <%= text_field_tag :city, params[:city]%>
</td>
 
<%= button_to "Save Info", action: "create" %> 


 <% end %>

<%= link_to 'Back', userinfos_path, method: :create %>

demo/app/views/userinfos/search.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<h1>Welcome to Tweet Trend</h1>
<p>You can search tweets by keyword!</p>

<table>

  <%= form_tag userinfos_search_path, :method => 'get' do %>
      <tr>
        <td>
          <%= label_tag :search, "Keyword" %>
          <%= text_field_tag :search, params[:search] %>
        </td>
      </tr>
      <tr>
        <td>
          <%= label_tag :search, "Country" %>
          <%= text_field_tag :country, params[:country] %>
        </td>
      </tr>
      <tr>
        <td>
          <%= label_tag :search, "City" %>
          <%= text_field_tag :city, params[:city] %>
        </td>
      </tr>
      <tr>
        <td>
          <%= submit_tag "Search", :text => nil %>
        </td>
      </tr>
  <% end %>


</table>

<%= form_tag userinfos_path, :method => 'get' do %>


    <%= button_to "Personal Profile", action: "index" %>
    <p id="notice"><%= notice %></p>
<% end %>

<%= form_tag destroy_user_session_path, :method => 'get' do %>


    <%= button_to "Sign Out" %>

<% end %>



<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({provider: {}, internal: {id: 'map'}}, function () {
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        polyline = <%=raw @line.to_json %>;
        handler.addPolyline(polyline, {
            strokeColor: '#FFFFEE', strokeOpacity: 1,
            strokeWeight: 1
        });
        handler.bounds.extend(polyline[0]);
        handler.bounds.extend(polyline[polyline.length - 1]);
        handler.fitMapToBounds();

    });
</script>
<% if params[:search] == "" %>
    Keyword is needed.
<% end %>
<% if params[:search] != "" %>
    <% if @tweets != nil && @tweets != [] %>
        <p id="notice">Tweets found!</p>
        <table>
          <thead>
          <tr>

            <th>Text</th>

            <th>Latitude</th>
            <th>Longitude</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @tweets.each do |tweet| %>
              <tr>

                <td><%= tweet[:text] %></td>

                <td><%= tweet[:lat] %></td>
                <td><%= tweet[:lng] %></td>

              </tr>
          <% end %>
          </tbody>
        </table>

        <br>
    <% else %>
        <p id="notice">Tweets not found!</p>
    <% end %>
<% end %>

demo/app/views/userinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @userinfo.user_name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @userinfo.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @userinfo.city %>
</p>

<p>
  <strong>Age:</strong>
  <%= @userinfo.age %>
</p>

<%= link_to 'Edit', edit_userinfo_path(@userinfo) %> |
<%= link_to 'Back', userinfos_path %>